### ISSUE TITLE
No twitter handle messes up koios member cards

### ISSUE THREAD

**Issue by Corwin96** [koiosonline/app.koios.world#105]
Discord message: https://discord.com/channels/758719930383597608/801480315800780830/889228021293269014
![image](https://user-images.githubusercontent.com/33621431/133940142-dc86184f-e09d-4bac-bbed-a6c72c0fded1.png)

Twitter image links to twitter homepage, maybe remove if no twitter.

**Comment by Rowin206** [comment]
@superstephan1 Could you take this one? Just don't render Twitter if there is no twitter account.
